import json
from pathlib import Path
from datetime import datetime, timezone
root=Path('work/se-workflow'); pack=root/'sources/pressman-practitioners-cn'; reg=root/'registry'; wf=root/'workflow-b'
for p in [reg,pack/'cards',wf/'handbook',wf/'templates']:
    p.mkdir(parents=True,exist_ok=True)
inv=json.loads((pack/'inventory.json').read_text(encoding='utf-8'))
segs=[json.loads(x) for x in (pack/'segments.jsonl').read_text(encoding='utf-8').splitlines()]
def seg(file_suffix,start):
    return next(x for x in segs if x['file'].endswith(file_suffix) and x['start_line']==start)
def u(n,title,domain,typ,purpose,trigger,ins,outs,steps,checks,antis,tail,seg,secondary=[]):
    return {'ku_id':f'KU-{n:04d}','segment_id':seg['segment_id'],'book_id':inv['book_id'],'title':title,'lifecycle_phase':domain,'secondary_domains':secondary,'knowledge_type':typ,'confidence':'medium','merge_status':'NEW','status':'seed_draft','purpose':purpose,'trigger':trigger,'inputs':ins,'outputs':outs,'procedure':steps,'checks':checks,'anti_patterns':antis,'tailoring':tail,'source_locator':seg['source_locator'],'needs_review':True}
units=[
u(1,'Process framework','governance','method','Establish controlled communication, planning, modeling, construction, deployment, and umbrella activities.','Starting any nontrivial product or process improvement.',['Business need','Stakeholders','Constraints'],['Process map','Umbrella activity plan'],['Define framework activities.','Select a process flow.','Attach quality, configuration, measurement, and risk activities.','Review fit each iteration.'],['Every activity has owner and artifact.','Deviations are recorded.'],['Adopting heavy process under high uncertainty.'],{'can_lighten':True,'cannot_remove':True,'light':'One-page map plus weekly review.','heavy':'Documented process plus audit.'},seg('1-200.md',428),['planning','quality']),
u(2,'Practice principles','quality','principle','Keep engineering work value-centered, simple, clear, change-aware, and reusable.','Making scope, design, implementation, or review trade-offs.',['Goals','Constraints','User evidence'],['Decision records','Design choices'],['Clarify value.','Prefer simplest credible design.','Make intent explicit.','Plan for likely change.','Reuse proven patterns when cheaper.'],['Decisions show value and risk.'],['Confusing novelty with value.'],{'can_lighten':True,'cannot_remove':True,'light':'PR decision notes.','heavy':'ADR plus review.'},seg('1-200.md',428),['design']),
u(3,'Stakeholder collaboration','teamwork','method','Align goals, vocabulary, risks, and decision authority.','Cross-functional work or unclear ownership.',['Problem statement','Stakeholders'],['Communication plan','Decision register'],['Identify stakeholders.','Name decision owners.','Select channels.','Record assumptions and issues.'],['No decision lacks an owner.'],['Meetings replacing written decisions.'],{'can_lighten':True,'cannot_remove':True,'light':'Shared decision log.','heavy':'Steering committee.'},seg('1-200.md',1117),['problem-framing']),
u(4,'Estimation','planning','method','Reduce uncertainty through decomposition, history, capacity, and confidence ranges.','Scoping, proposals, or iteration planning.',['Scope','History','Capacity'],['Range estimate','Assumptions'],['Decompose work.','Estimate size.','Adjust for productivity and risk.','Compare history.','Re-estimate at gates.'],['Range and assumptions explicit.'],['One-point estimate treated as promise.'],{'can_lighten':True,'cannot_remove':True,'light':'Rolling-wave story points.','heavy':'Model plus contingency.'},seg('1-200.md',1788)),
u(5,'Risk management','risk','method','Identify, rank, mitigate, monitor, and escalate uncertain conditions.','Project start or high-risk choice.',['Context','Assumptions'],['Risk table','Response plan'],['Identify risks.','Estimate probability/impact.','Rank exposure.','Define mitigation and trigger.','Review at gates.'],['High exposure has owner and trigger.'],['Risks without response thresholds.'],{'cannot_remove':True,'light':'Top-ten table.','heavy':'Quantified independent review.'},seg('1-200.md',2425),['planning'])
]
for n,title,domain,typ,purpose,trigger,ins,outs,steps,checks,antis,tail,suffix,start,secondary in [
(6,'Task tracking','planning','method','Convert scope into dependency-aware tracked work.','Approved objectives and constraints.',['WBS','Dependencies','Capacity'],['Schedule','Progress signals'],['Define milestones.','Refine tasks.','Model critical path.','Allocate buffer.','Track output-based progress.'],['Critical path known.','Variance triggers action.'],['Percent complete without verified output.'],{'can_lighten':True,'cannot_remove':True,'light':'Board and DoD.','heavy':'Earned value.'},'1-200.md',2977,['governance']),
(7,'Quality assurance','quality','method','Prevent and remove defects through reviews, standards, metrics, and correction.','Before costly implementation or release.',['Work product','Checklist','Reviewers'],['Findings','Actions','Metrics'],['Set quality goals.','Use entry/exit checklists.','Hold focused review.','Log defects.','Track escapes.'],['Findings have owner.'],['Ceremonial review.'],{'can_lighten':True,'cannot_remove':True,'light':'Peer checklist.','heavy':'Formal inspection.'},'1-200.md',3413,['verification']),
(8,'Configuration control','governance','method','Control versions, baselines, changes, builds, audits, and status.','Multiple contributors or release obligations.',['Baselines','Changes','Repository'],['Version history','Audit trail'],['Identify items.','Control branches.','Baseline artifacts.','Assess impact.','Audit releases.'],['Release maps to approved sources.'],['Uncontrolled hotfixes.'],{'cannot_remove':True,'light':'Protected trunk and PR.','heavy':'CCB and traceability.'},'1-200.md',4029,['release']),
(9,'Feasibility framing','problem-framing','decision_rule','Test business, technical, economic, and operational feasibility.','New product or major shift.',['Objective','Concept','Constraints'],['Proceed/pivot/stop','Success criteria'],['State problem.','Measure success.','Test viability.','Estimate benefit/risk.','Choose direction.'],['Kill criteria exist.'],['Solution before feasibility.'],{'can_lighten':True,'cannot_remove':True,'light':'Problem/solution page.','heavy':'Business case.'},'1-200.md',4403,['requirements','risk']),
(10,'Requirements elicitation','requirements','method','Turn needs into prioritized verifiable requirements and acceptance criteria.','Inception, scope change, ambiguity.',['Stakeholders','Scenarios','Constraints'],['Requirements','Acceptance criteria'],['Elicit scenarios.','Separate need and solution.','Prioritize conflicts.','Write testable requirements.','Review completeness/testability.'],['Each requirement has verification method.'],['Solution recorded as need.'],{'can_lighten':True,'cannot_remove':True,'light':'Requirement cards.','heavy':'SRS and traceability.'},'1-200.md',4917,['verification']),
(11,'Modular quality','architecture','principle','Manage coupling, cohesion, hiding, abstraction, and interfaces for changeability.','Component boundaries or refactor.',['Requirements','Domain model'],['Component model','Contracts'],['Assign cohesive responsibility.','Minimize coupling.','Hide details.','Define interfaces.','Evaluate quality attributes.'],['Changes localize.'],['Hidden dependencies across layers.'],{'can_lighten':True,'cannot_remove':True,'light':'Ownership/interface tests.','heavy':'ADR and review.'},'201-400.md',407,['design','maintenance']),
(12,'Layered design','design','method','Design data, architecture, interface, UX, and component logic coherently.','Nontrivial approved scope.',['Requirements','Analysis model'],['Design model','Interfaces'],['Design data.','Map architecture.','Design interfaces/UX.','Specify components.','Review traceability.'],['Requirement maps to design or backlog.'],['UI hides unavailable flow.'],{'can_lighten':True,'cannot_remove':True,'light':'Sketch/API/tests.','heavy':'Design document.'},'201-400.md',823,['architecture']),
(13,'Test case design','verification','method','Combine structural and behavioral techniques for risk coverage.','Complex/high-risk logic.',['Source/design','Requirements','Risks'],['Cases','Coverage evidence'],['Model behavior.','Apply boundaries/equivalence.','Add path/branch tests.','Add negative cases.','Prioritize by risk.'],['Every case has expected result.'],['Coverage without assertions.'],{'can_lighten':True,'cannot_remove':True,'light':'Risk-focused branch tests.','heavy':'Critical-module structural suite.'},'201-400.md',1897,['construction']),
(14,'Verification strategy','verification','method','Sequence unit, integration, validation, system, and regression testing.','Feature or release candidate.',['Requirements','Build','Risk model'],['Strategy','Release recommendation'],['Define unit/integration approach.','Verify scenarios.','Add performance/security/recovery.','Automate regression.','Set exit criteria.'],['Blockers triaged.'],['Integration deferred to end.'],{'cannot_remove':True,'light':'Thin E2E plus regression.','heavy':'Independent V&V.'},'201-400.md',2770,['release'])
]:
    units.append(u(n,title,domain,typ,purpose,trigger,ins,outs,steps,checks,antis,tail,seg(suffix,start),secondary))
(reg/'lifecycle-spine.json').write_text(json.dumps({'schema_version':1,'updated_at':datetime.now(timezone.utc).isoformat(),'domains':['problem-framing','planning','risk','requirements','architecture','design','construction','verification','release','operations','feedback','maintenance','quality','governance','teamwork']},ensure_ascii=False,indent=2)+'\n',encoding='utf-8')
with (reg/'sources.jsonl').open('w',encoding='utf-8',newline='\n') as f: f.write(json.dumps({'book_id':inv['book_id'],'title':inv['title'],'type':'lifecycle-overview','status':'seed_integrated','files':[x['path'] for x in inv['files']],'segments':len(segs),'knowledge_units':len(units),'confidence':'medium'},ensure_ascii=False)+'\n')
(reg/'segments.jsonl').write_text(''.join(json.dumps(x,ensure_ascii=False,sort_keys=True)+'\n' for x in segs),encoding='utf-8')
(reg/'knowledge-units.jsonl').write_text(''.join(json.dumps(x,ensure_ascii=False,sort_keys=True)+'\n' for x in sorted(units,key=lambda z:z['ku_id'])),encoding='utf-8')
(reg/'conflicts.jsonl').write_text('',encoding='utf-8')
for x in units:
    lines=[f"# {x['ku_id']}: {x['title']}",'',f"- book_id: `{x['book_id']}`",f"- segment_id: `{x['segment_id']}`",f"- lifecycle_phase: `{x['lifecycle_phase']}`",f"- secondary_domains: `{', '.join(x['secondary_domains']) or '-'}`",f"- knowledge_type: `{x['knowledge_type']}`",f"- merge_status: `{x['merge_status']}`",f"- status: `{x['status']}`",'',x['purpose'],'',f"Trigger: {x['trigger']}",'','Inputs']+[f'- {v}' for v in x['inputs']]+['','Outputs']+[f'- {v}' for v in x['outputs']]+['','Procedure']+[f'{i}. {v}' for i,v in enumerate(x['procedure'],1)]+['','Checks']+[f'- {v}' for v in x['checks']]+['','Anti-patterns']+[f'- {v}' for v in x['anti_patterns']]+['',f"Tailoring: {x['tailoring']}",'',f"Source: `{x['source_locator']}`"]
    (pack/'cards'/f"{x['ku_id']}.md").write_text('\n'.join(lines)+'\n',encoding='utf-8')
print(json.dumps({'segments':len(segs),'knowledge_units':len(units)},ensure_ascii=False))


